import React from 'react';

export default function AuditLogsView({ theme, isDarkMode, auditLogs }) {
  return (
    <div className="space-y-6 animate-fadeIn">
      <div>
        <h2 className={`text-xl font-extrabold tracking-tight uppercase ${theme.textTitle}`}>Immutable System Audit Logs</h2>
        <p className={`text-xs mt-1 ${theme.textMuted}`}>Cryptographic track record of action timestamps generated by master access nodes</p>
      </div>

      <div className={`border rounded-2xl overflow-hidden ${theme.tableBg}`}>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse min-w-[650px]">
            <thead>
              <tr className={`font-extrabold border-b uppercase tracking-wider ${theme.th}`}>
                <th className="p-4">Timestamp Matrix</th>
                <th className="p-4">Authorization Identity</th>
                <th className="p-4">Operation Dispatched</th>
                <th className="p-4 text-right">IP Network Node</th>
              </tr>
            </thead>
            <tbody className={`divide-y font-mono text-xs ${isDarkMode ? 'divide-slate-800/60' : 'divide-slate-200'}`}>
              {auditLogs.map(log => (
                <tr key={log.id} className={isDarkMode ? 'hover:bg-slate-800/20' : 'hover:bg-slate-50'}>
                  <td className="p-4 text-slate-400">{log.timestamp}</td>
                  <td className={`p-4 font-bold ${theme.textTitle}`}>{log.admin}</td>
                  <td className="p-4 text-slate-400 font-sans font-medium">{log.action}</td>
                  <td className="p-4 text-right text-slate-400">{log.ip}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}